name: Sync GitHub Activity to Notion

on:
  workflow_dispatch:
  schedule:
    # Run at 01:00 UTC MON-FRI
    - cron: "0 1 * * 1-5"

jobs:
  sync-github-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run script to sync data
        run: |
          python notion-github-sync.py
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
